### ISSUE TITLE
Publish this in npm and bower

### ISSUE THREAD

**Issue by xogeny** [omuses/moijs#1]

**Comment by xogeny** [comment]
I'm going to create a fork of this to improve a few things.  Of course, if you ever want to merge the fork back in, just let me know.  My plan is to improve the Node.js and `webpack` support.

**Comment by xogeny** [comment]
One thing I didn't mention.  As part of that, I will push it to NPM.

**Comment by javedulu** [comment]
Let me know if do can help have used this package extensively 🙂 ...
